spring.application.name=demo

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update

spring.main.allow-circular-references=true
spring.config.import=optional:file:.env[.properties]
jwt.access.secret=${JWT_ACCESS_SECRET}
jwt.refresh.secret=${JWT_REFRESH_SECRET}

jwt.access.expiration=${JWT_ACCESS_EXPIRATION}
jwt.refresh.expiration=${JWT_REFRESH_EXPIRATION}

aws.access-key=${AWS_ACCESS_KEY}
aws.secret-key=${AWS_SECRET_KEY}
aws.region=${AWS_REGION}
aws.bucket-name=${AWS_BUCKET_NAME}

spring.servlet.multipart.max-file-size=10GB
spring.servlet.multipart.max-request-size=10GB